### ISSUE TITLE
1.20.2?

### ISSUE THREAD

**Issue by Xerox0987** [CyberFlameGO/viewmodel-changer#105]
### What is your question?

Hello i love this mod and i wouald like it for when i play purity vanilla but the server is 1.20.2. Do you mind updating this mod? Thank you in advance

**Comment by CyberFlameGO** [comment]
Heyy @Xerox0987 - could you please give [this build](https://github.com/CyberFlameGO/viewmodel-changer/actions/runs/7326280498/artifacts/1134668025) a try and let me know if it works? When you unzip it, use the `viewmodel-1.9.2.jar` file (**__not__** the `viewmodel-1.9.2-sources.jar`). Thanks so much, sorry for the wait, and Merry Christmas! :)

**Comment by Xerox0987** [comment]
> Heyy @Xerox0987 - could you please give [this build](https://github.com/CyberFlameGO/viewmodel-changer/actions/runs/7326280498/artifacts/1134668025) a try and let me know if it works? When you unzip it, use the `viewmodel-1.9.2.jar` file (**__not__** the `viewmodel-1.9.2-sources.jar`). Thanks so much, sorry for the wait, and Merry Christmas! :)

Oh well thank you so much for updating it I was actually surprised that someone replied lol. Merry Christmas to you too and I hope you are having a wonderful holiday,❤️
Im currently on vacation so im unable to try it right now but I will when I get home sorry

**Comment by nemyxo** [comment]
thats one long ass vacation

**Comment by CyberFlameGO** [comment]
Closing as completed - if there are indeed any issues I'll circle back and fix them

**Comment by Xerox0987** [comment]
> thats one long ass vacation

I'm back now :)
