### ISSUE TITLE
Pls uptdate 1m16

### ISSUE THREAD

**Issue by Eramon0** [CyberFlameGO/viewmodel-changer#138]
### What is your question?

I like to pvp with your mod, but there is a minor problem. In 1.16 snapshot there is no "swing" mode, and it kinda sad, cuz it is pretty cool. It would be nice if u update 1.16.5 to add this options, because i can't use versions higher. Ty

**Comment by CyberFlameGO** [comment]
It might be a *bit* tedious to backport those changes - are you still interested in this change? I could have a look at trying to implement it and get back to you if this is still something you'd like.

**Comment by CyberFlameGO** [comment]
Closing due to this issue being stale and requiring a bit too much effort for me to do unnecessarily
