### ISSUE TITLE
Crashando na 1.19.4

### ISSUE THREAD

**Issue by LOSTXZZ** [CyberFlameGO/viewmodel-changer#146]
### What is your question?

O view model esta crashando meu jogo, sou pirata e jogo na 1.19.4

**Comment by CyberFlameGO** [comment]
I'm assuming that's 1.19.4 crashing the game (sorry! Google Translate wasn't too helpful)? I think I know why that's happening - would you like this to be fixed or have you moved onto a newer version (where the problem doesn't occur)?

**Comment by CyberFlameGO** [comment]
Closing due to this issue being stale and requiring a bit too much effort for me to do unnecessarily
