### ISSUE TITLE
Fabric loader version 0.16.1 does not exist (1.21)

### ISSUE THREAD

**Issue by lilmayu** [CyberFlameGO/viewmodel-changer#159]
### Code of Conduct

- [X] I have read and agree to the project's [Code of Conduct](https://github.com/CyberFlameGO/.github/blob/master/docs/CODE_OF_CONDUCT.md)

### What improvements would you like to see?

![obrazek](https://github.com/user-attachments/assets/ee6d4fce-8e86-4feb-a740-dc0caa36e992)

https://github.com/CyberFlameGO/viewmodel-changer/blob/53daab96fd6c0bfdaa9d6223acfccd9db82dd043/src/main/resources/fabric.mod.json#L26

### What changes are you suggesting?

Fixing it

### Additional information

I guess there could be that version when you updated it? No idea.

**Comment by CyberFlameGO** [comment]
Oh whoops! I'll fix that now - give me 2min

**Comment by lilmayu** [comment]
No stress lol I was just porting this mod for myself to forge 1.18.2 and I needed to see what config values would be good

**Comment by CyberFlameGO** [comment]
Ahhh fair enough - thanks so much for spotting that!! Fixed in https://github.com/CyberFlameGO/viewmodel-changer/releases/tag/v1.10.1
