### ISSUE TITLE
I cant load feather with viewmodel mod 

### ISSUE THREAD

**Issue by Pavlakos-1** [CyberFlameGO/viewmodel-changer#166]
### What is your question?

can someone help me fix it please ? ( i will send screen shot when i put the mod what happens ) 
![121212](https://github.com/user-attachments/assets/9eb8168f-27e5-4ac0-a0ca-76d73a6de017)
![Screenshot 2024-08-17 093950](https://github.com/user-attachments/assets/cf46f2ad-6176-41c5-8d17-b72e871c29fb)

**Comment by CyberFlameGO** [comment]
Thanks for this report - could you isolate the mod on its own to determine whether it is indeed this mod, and provide your Fabric API mod version, modloader version, and MC version? If you're using a custom Java runtime/a custom launcher please include your Java distribution too if possible!
