### ISSUE TITLE
1.19.3 Support

### ISSUE THREAD

**Issue by tpopbpmg** [CyberFlameGO/viewmodel-changer#2]
### What is your question?

Could you make support for 1.19.3?

**Comment by CyberFlameGO** [comment]
Whoops, got a compilation error - probably should've put it in an IDE and tried things properly first. I'm working on fixing it now, may take awhile but I'll (hopefully) get there in the end.

**Comment by CyberFlameGO** [comment]
I'm having quite a bit of trouble with the new JOML Vector3d library it uses so I'm not able to do it myself but the issue's pinned so someone else may be able to contribute to it in the branch this issue's linked to

**Comment by CyberFlameGO** [comment]
Seems to be fixed as of [13549c8](https://github.com/CyberFlameGO/viewmodel-changer/commit/13549c8f7fec9db3ce84f2582e12f2e96c11f20f) so I'll quickly compile and publish a release
