### ISSUE TITLE
Crashing on Pojavlauncher with the viewmodel mod

### ISSUE THREAD

**Issue by Lefted66** [CyberFlameGO/viewmodel-changer#91]
### Code of Conduct

- [X] I have read and agree to the project's [Code of Conduct](https://github.com/CyberFlameGO/.github/blob/master/docs/CODE_OF_CONDUCT.md)

### What improvements would you like to see?

I have download the viewmodel mod the 1.6 version one and i putted it in my mods folder and when i load pojavlauncher my game crashes for some reason i have seen that in curseforge the mod is in beta i would like to see if i can get this fixed.

### What changes are you suggesting?

I want the mod to be fixed with the crashes

**Comment by Lefted66** [comment]
CyberFlameGo please help i need this to be fixed

**Comment by CyberFlameGO** [comment]
Hi there @Lefted66! Unfortunately the build for 1.20 is broken - I'd recommend that you switch over to 1.20.1 which has a functional build :)

**Comment by Lefted66** [comment]
Ok
