### ISSUE TITLE
Add keybind configuration to the mod

### ISSUE THREAD

**Issue by ItzExvirnity** [CyberFlameGO/viewmodel-changer#92]
### Code of Conduct

- [X] I have read and agree to the project's [Code of Conduct](https://github.com/CyberFlameGO/.github/blob/master/docs/CODE_OF_CONDUCT.md)

### What improvements would you like to see?

I don't really think of any improvements so sorry for not giving any explanation here. 

### What changes are you suggesting?

Will you add a key bind into the Controls Menu in Minecraft that allows you to change the key you press to open the menu? I am asking for this because when I am typing something into chat and I press the key to open the menu it just opens, can you make it so it only happens when nothing is open? For example In-game Chat

### Additional information

Anyway, this mod helped me a lot with PVP since I was able to reduce how much stuff like my hand or shield I see on the screen while playing | Thanks for making this mod! It helped a lot

**Comment by CyberFlameGO** [comment]
Might add one myself if mod gains enough interest for it/if I find the time - at this time I am quite swamped with IRL stuff though but I'm happy to review/merge any code contributions if anyone else wants to implement it

**Comment by Mattem300** [comment]
Alright, I hope you get free from all the stuff happening IRL soon, have a great day

**Comment by CyberFlameGO** [comment]
For future reference - https://fabricmc.net/wiki/tutorial:keybinds
